name: Deploy to AWS

on:
  push:
    branches: [cloud-formation-demo]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Load env
        run: |
          echo "alo ${{ secrets.AWS_ACCESS_KEY_ID }} "
          echo "alo 2 ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # - name: Install dependencies (replace with your build steps)
      #   run: npm install # Or your specific build command

      # - name: Build and deploy to AWS (replace with your deployment commands)
      #   run: npm run build && aws s3 cp --recursive build s3://your-bucket-name/ # Or your deployment commands
