name: Deploy to AWS

on:
  push:
    branches: [cloud-formation-demo]

env:
  AWS_REGION: ap-southeast-1
  AWS_ROLE: arn:aws:iam::081322589116:role/github-action-role
  STACK: cloud-driver-stack
  FILE_PATH: cloud-formation-demo/init.yaml
  S3_BUCKET_NAME: cloud-driver-bucket

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
 
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Delete forcely S3 bucket
        run: aws s3 rb s3://${{ env.S3_BUCKET_NAME }} --force  --only-show-errors

      - name: Delete old stack 
        run: aws cloudformation delete-stack --stack-name ${{ env.STACK }}

      - name: Create new stack
        if: success()
        run: aws cloudformation create-stack --stack-name ${{ env.STACK }} --template-body file://${{ env.FILE_PATH }}
