name: Deploy to AWS

on:
  push:
    branches: [cloud-formation-demo]

env:
  AWS_REGION: ap-southeast-1
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::081322589116:role/github-action-role
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Print assumed role
        run: aws sts get-caller-identity

      - name: test location
        run: pwd 
        
      - name: Create stack
        run: aws cloudformation create-stack --stack-name cloud-driver-stack --template-body cloud-formation-demo/init.yml
     


